ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  ACTION_SPACE_CONFIG: v0
  AGENT_0:
    SENSORS: [RGB_SENSOR_FRONT,RGB_SENSOR_LEFT,RGB_SENSOR_RIGHT,RGB_SENSOR_BACK]
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR_FRONT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    UUID: front

  RGB_SENSOR_LEFT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 1.5707963, 0]
    UUID: left

  RGB_SENSOR_RIGHT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, -1.5707963, 0]
    UUID: right

  RGB_SENSOR_BACK:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 3.1415926, 0]
    UUID: back

TASK:
  TYPE: VLN-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: [
    INSTRUCTION_SENSOR,
    SHORTEST_PATH_SENSOR,
    VLN_ORACLE_PROGRESS_SENSOR
  ]
  INSTRUCTION_SENSOR_UUID: instruction
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, GO_TOWARD_POINT]
  MEASUREMENTS: [
    TOP_DOWN_MAP_VLNCE,
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL,
    NDTW,
    PATH_LENGTH,
    ORACLE_SUCCESS,
    STEPS_TAKEN
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  SPL:
    SUCCESS_DISTANCE: 3.0
  NDTW:
    GT_PATH: ./data/dataset/R2R_VLNCE_v1-3_preprocessed/val_unseen/val_unseen.json.gz
DATASET:
  TYPE: VLN-CE-v1
  SPLIT: val_unseen
  DATA_PATH: ./data/dataset/R2R_VLNCE_v1-3_preprocessed/val_unseen/val_unseen.json.gz
  SCENES_DIR: ./data/dataset/Matterport3D/scene_datasets/mp3d/v1/tasks
